services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:gateway
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - net
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:auth
    depends_on:
      - db
    expose:
      - 8081
    ports:
      - 8081:8081
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - net
  email:
    build:
      context: .
      dockerfile: ./apps/email/Dockerfile
      target: development
    command: npm run start:email
    expose:
      - 8082
    ports:
      - 8082:8082
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - net
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DATABASE= tmarket
      - PG_DATA= /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - db:/var/lib/postgresql/data
networks:
  net:
volumes:
  db:


